apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-demo
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: terraform-service
          servicePort: 80
